# Generated by Django 4.0.3 on 2022-04-02 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_album', to=settings.AUTH_USER_MODEL, verbose_name='Избранный альбом'),
        ),
        migrations.AddField(
            model_name='album',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Приват'),
        ),
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_photo', to=settings.AUTH_USER_MODEL, verbose_name='Избранное фото'),
        ),
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=True, verbose_name='Приват'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='webapp.album', verbose_name='Альбом'),
        ),
    ]
