# Generated by Django 4.0.3 on 2022-04-02 05:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_album_favorites_album_private_photo_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='favorites',
        ),
        migrations.AddField(
            model_name='album',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='favorites',
        ),
        migrations.AddField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
