# Generated by Django 4.0.3 on 2022-04-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_remove_album_favorites_album_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='webapp.album', verbose_name='Альбом'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
