# Generated by Django 4.0.3 on 2022-04-02 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_album_favorites_alter_photo_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
