# Generated by Django 4.0.3 on 2022-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_photo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='token',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
